### ISSUE TITLE
"Enable Pathtracing" crash game

### ISSUE THREAD

**Issue by andreluizgit** [BredaUniversityGames/DXX-Raytracer#8]
Please ... The game crash after to enable Pathtracing.

My GPU : RTX 3060 (DX12 Ultimate, Windows 11).

Note : only PBR enabled the game works and it show reflections.

Dump file ( [https://file.io/Nqr2aXqVts1I](https://file.io/Nqr2aXqVts1I) ) after to click "Enable Pathtracing" : 

![image](https://github.com/BredaUniversityGames/DXX-Raytracer/assets/22436084/f30d88bd-21b2-4d49-8555-9850e74aeded)

**Comment by Contingencyy** [comment]
Does it crash without any error message? It might be related or the same bug that we had reported in our discord support channel not too long ago. It was seemingly related to a graphics driver bug (actually a newer driver introduced this, so they reverted to an older one). Also I suggest you report bugs in our discord support channel, since that is more likely to be picked up by us. We do not actively work on this anymore, so we rarely look here.

**Comment by Contingencyy** [comment]
Fixed as of 1.1.0
